steps:
  # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
    - 'build'
    - '-t'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/zefir/zefir-server:$SHORT_SHA'
    - '.'

  # This step pushes the image to Artifact Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
    - 'push'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/zefir/zefir-server:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s/\$SHORT_SHA/${SHORT_SHA}/g" kubernetes.yaml

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
    - 'apply'
    - '-f'
    - 'kubernetes.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_REGION=europe-west1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=zefir-cluster'