apiVersion: apps/v1
kind: Deployment
metadata:
  name: zefir-server
spec:
  replicas: 1  # Number of replicas to create for your application
  selector:
    matchLabels:
      app: zefir-server
  template:
    metadata:
      labels:
        app: zefir-server
    spec:
      containers:
        - name: zefir-server
          image: gcr.io/PROJECT_ID/zefir/zefir-server:SHORT_SHA
          ports:
            - containerPort: 3000  # Port number on which your application listens      
---
apiVersion: v1
kind: Service
metadata:
  name: zefir-server-service
spec:
  selector:
    app: zefir-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000