apiVersion: apps/v1
kind: Deployment
metadata:
        name: zefir-server
spec:
        replicas: #replicaNumber#
        selector:
                matchLabels:
                        app: zefir-server
        template:
                metadata:
                        labels:
                                app: zefir-server
                spec:
                        containers:
                                - name: zefir-server
                                  image: zefirgameserver.azurecr.io/zefirgameserver
                                  ports:
                                          - containerPort: 3000
