apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
        name: zefir-server-ingress
        annotations:
                kubernetes.io/ingress.class: nginx
                cert-manager.io/cluster-issuer: cluster-issuer-name
                cert-manager.io/acme-challenge-type: http01
                nginx.ingress.kubernetes.io/rewrite-target: /
spec:
        rules:
                - host: 'server.iedre.dev'
                  http:
                          paths:
                                  - path: /
                                    pathType: Prefix
                                    backend:
                                            service:
                                                    name: zefir-server-service
                                                    port:
                                                            number: 3000
        tls:
                - hosts:
                          - server.iedre.dev
                  secretName: secret-name
