apiVersion: v1
kind: Service
metadata:
        name: zefir-server-service
spec:
        selector:
                app: zefir-server
        ports:
                - protocol: TCP
                  port: 3000
                  targetPort: 3000
