apiVersion: v1
kind: Service
metadata:
        name: zefirgameserver
spec:
        type: LoadBalancer
        ports:
                - port: 3000
        selector:
                app: zefirgameserver
